const questions=[
    {
         "question":"1.What is Babel?",
       
        "optionA":" A JavaScript transpiler",
        "optionB": "A JavaScript interpreter",
        "optionC": "A JavaScript Compiler",
        "optionD":"None of the above",
         "answer":"A JavaScript Compiler",
    },
    {
         "question":"2.React was originally created by ?",
        "optionA":"Jordan Walke",
        "optionB":"  Rasmus Lerdorf",
        "optionC":" Miško Hevery",
        "optionD":"None of the above",    
        "answer":"Jordan Walke",
    },
    {
         "question":"3.React is used mainly for building?",
        "optionA":" Database",
        "optionB":" User interface",
        "optionC":" Connectivity",
        "optionD":"Design platform",
        "answer":" User interface" ,
    },
    {
         "question":"4.Which of the following keyword is used to create a class inheritance?",
        "optionA":"Create",
        "optionB":"Inherits",
        "optionC":"Extends",
        "optionD":"This",
        "answer":"Extends",
    },
    {
         "question":"5.Which of the following acts as the input of a class-based component?",
        "optionA":"Class",
        "optionB":"Factory",
        "optionC":"Render",
        "optionD":"Props",
       "answer":"Props",
    },
    {
         "question":"6.A class is a type of function, but instead of using the keyword function to initiate it, which keyword do we use?",
        "optionA":"Constructor",
        "optionB":"Class",
        "optionC":"Object",
        "optionD":"DataObject",
       "answer":"Class",
    },
    {
         "question":"7............... port is the default where the webpack-dev-server will run.",
        "optionA":"3030",
        "optionB":"8080",
        "optionC":"3306",
        "optionD":"3000",
         "answer":"8080",
    },
    {
         "question":"8.Which of the following command is used to create a react app?",
        "optionA":"install -g create-react-app",
        "optionB":" npm install create-react-app",
        "optionC":" npm install -g create-react-app",
        "optionD":"None of the Above",
        "answer":" npm install -g create-react-app",
    },
    {
         "question":"9.We can prevent default behavior in React using ............",
        "optionA":" revokeDefault()",
        "optionB":"preventDefault()",
        "optionC":" avoidDefault()",
        "optionD":" None of the Above",
   "answer":"preventDefault()",
    },
    {
         "question":"10.A state in React.js is also known is ..............",
        "optionA":"  A permanent storage.",
        "optionB":" An Internal storage of the component.",
        "optionC":"An External storage of the component.",
        "optionD":"All of the above",
       "answer":" An Internal storage of the component.",
    },
    {
         "question":"11.In React what is used to pass data to a component from outside?",
        "optionA":" setState",
        "optionB":" render with props",
        "optionC":"arguments",
        "optionD":"PropTypes",
        "answer":" setState",
    },
    {
         "question":"12.ReactJS uses _____ to increase performance",
        "optionA":" Original DOM",
        "optionB":"Virtual DOM",
        "optionC":"Both 1 & 2",
        "optionD":" None of above",
        "answer":"Virtual DOM",
    },
    {
         "question":"13.Which function is used to change the state of react component?",
        "optionA":"this.State{}",
        "optionB":"this.setState",
        "optionC":" this.setChangeState",
        "optionD":"None of the Above",
        "answer":"this.setState",
    },
    {
         "question":"14.What is the smallest building block of ReactJS?",
       
        "optionA":" props",
        "optionB":"elements",
        "optionC":"components",
        "optionD":"None of the Above",
        "answer":"components",
    },
    {
         "question":"15.What are the two ways to handle data in React?",
       
        "optionA": "State&Props",
        "optionB": "Services & Components",
        "optionC": "State & Services",
        "optionD": "State & Component",
         "answer": "State&Props",
    },
]
export default questions